config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root "posts#index"
end

app/models/post.rb
class Post
  include Mongoid::Document

  CATEGORIES = %w[literature math auto it philosophy].freeze

  validates :title, :content, presence: true
  validates :content, length: { minimum: 5 }
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :categories, presence: true

  field :title, type: String
  field :content, type: String
  field :rating, type: Integer, default: 0
  field :categories, type: Array
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  responders :flash

  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  expose_decorated :posts, -> { filtered_posts }
  expose_decorated :post

  def new
  end

  def create
    post.save

    respond_with post
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
    post.update_attributes(post_params)

    respond_with post, location: posts_path
  end

  def destroy
    post.destroy

    respond_with post, location: posts_path
  end

  private

  def filtered_posts
    @filtered_posts ||= params[:filter] ? PostFilterQuery.new(Post.all, filter_params).all : Post.all
  end

  def filter_params
    params.require(:filter).permit(:rating_filtration_value, :rating_sort_direction, categories: [])
  end

  def post_params
    params.require(:post).permit(:title, :content, :rating, categories: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/_navbar.html.slim
nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span class="sr-only" Toggle navigation
      = link_to "Mongo Base", root_path, class: "navbar-brand"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MongoProject
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/navbar"
    .container
        = yield

app/views/posts/_filter_form.html.slim
.filter-form
  = simple_form_for :filter, url: posts_path, method: :get  do |f|
    = f.input :rating_filtration_value, as: :integer, input_html: { min: 0, max: 5 }
    = f.input :categories, collection: Post::CATEGORIES, as: :check_boxes, include_hidden: false
    = f.input :rating_sort_direction, collection: %w[desc asc], include_blank: false
    = f.button :submit, "Apply"

app/views/posts/_form.html.slim
= simple_form_for(post.to_model) do |f|
  = f.error_notification

  = f.input :title, required: true

  = f.input :content, as: :text, required: true

  = f.input :rating, as: :integer

  = f.input :categories, collection: Post::CATEGORIES, as: :check_boxes, include_hidden: false

  = f.button :submit

app/views/posts/_post.html.slim
.post.list-group-item.list-group-item-action.flex-column.align-items-start
  .justify-content-between
    h5 class="mb-1"
      = link_to "#{post.title}", post
    small
      = link_to "Edit", edit_post_path(post), class: "action-link"
      = link_to "Delete", post, method: :delete, data: { confirm: "Are you sure?" }, class: "action-link"
  .content-block
    p class="mb-2"
      = post.content
    p class="mb-1"
      = post.assigned_categories
    small
      span Rating: #{post.rating}

app/views/posts/edit.html.slim
.block
  h1 Edit #{post.title}
  = render "posts/form"

app/views/posts/index.html.slim
.row
  .col-md-3.block
    = render "posts/filter_form"
  .col-md-9.block
    h1 Posts
    = link_to "Add new post", new_post_path
    .list-group
      = render posts

app/views/posts/new.html.slim
.block
  h1
    | Post#new
  = render "posts/form"

app/views/posts/show.html.slim
.block
  h1
    = post.title
  p
    = post.content
  p Rating: #{post.rating}